[build]
  base = "frontend"
  command = "rm -rf node_modules package-lock.json && npm install --legacy-peer-deps && npm run build"
  publish = "dist"

# Optional: provide a redirect for SPA (Netlify will still use _redirects in dist)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
